services:
  sluice-server:
    build:
      context: .
      target: server
    image: ghcr.io/ggos3/sluice-server
    ports:
      - "18080:18080"
    restart: unless-stopped

  sluice-agent:
    build:
      context: .
      target: agent
    image: ghcr.io/ggos3/sluice-agent
    environment:
      SLUICE_PROXY_HOST: 192.168.1.100
      SLUICE_PROXY_PORT: "18080"
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
